/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PoliceDepartment;

/**
 *
 * @author sahilpadyal
 */

import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import utilPackage.Helper;
import utilPackage.S3BucketOperations;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.CitizenStatus;
import model.Evidence;
import model.Person;
import utilPackage.CurrentSession;
import utilPackage.ResultSetMapper;
import utilPackage.ValidationHelper;
public class CitizenStatusPortal extends javax.swing.JFrame {

    /**
     * Creates new form mainPoliceDept
     */
    Integer currentCaseId;
    public CitizenStatusPortal() {
        initComponents();
  
        
        try {
          
            List<CitizenStatus> objList = Helper.getResultSet(CitizenStatus.class, "citizen_status");
            
            if(objList != null) {
                for(CitizenStatus i : objList){
                    Integer statusId = i.getStatusId();
                    String name = i.getPerson().getName();
                    String status = i.getStatus();
                    Integer caseId = i.getCaseId();
                    Integer wantedLevel = i.getWantedLevel();
                    
                    DefaultTableModel tblModel = (DefaultTableModel)jBackgroundTable.getModel();
                    Object[] obj = {statusId, name, status, caseId, wantedLevel};
                    tblModel.addRow(obj);                   
                }
            }
            
            
        } catch (InstantiationException ex) {
            Logger.getLogger(CasePortalCaptain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jBackgroundTable = new javax.swing.JTable();
        jUpdateButton = new javax.swing.JButton();
        createEvidence = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jImagePath = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCaseId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jStatus = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jWantedLevel = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/backs.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/cross.png"))); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 200, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 6, 365, -1));

        jBackgroundTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Status ID", "Name", "Status", "Case ID", "Wanted Level"
            }
        ));
        jBackgroundTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBackgroundTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jBackgroundTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 379, 872, 236));

        jUpdateButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jUpdateButton.setForeground(new java.awt.Color(51, 102, 0));
        jUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/updatepatient.png"))); // NOI18N
        jUpdateButton.setText("Update");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 301, -1, -1));

        createEvidence.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        createEvidence.setForeground(new java.awt.Color(51, 102, 0));
        createEvidence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/addpatient.png"))); // NOI18N
        createEvidence.setText("Create");
        createEvidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEvidenceActionPerformed(evt);
            }
        });
        getContentPane().add(createEvidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 301, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 373, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 6, -1, 40));
        getContentPane().add(jImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 234, 42, 48));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Background Data");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 6, 388, 95));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Case ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 64, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 173, 75, -1));

        jCaseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCaseIdActionPerformed(evt);
            }
        });
        getContentPane().add(jCaseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 143, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 173, 64, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 102, 0));
        jLabel8.setText("Wanted Level");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 87, -1));

        jStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suspect", "Victim", "Witness", " " }));
        getContentPane().add(jStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 144, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 70, -1));

        jWantedLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        getContentPane().add(jWantedLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 144, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        
        if(ValidationHelper.isEmptyOrNullString(jCaseId.getText())) {
                JOptionPane.showMessageDialog(this, "Case ID cannot be null.");
                return;
            }
            
            if(ValidationHelper.isEmptyOrNullString(jWantedLevel.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Wanted Level cannot be null.");
                return;
            }
            
            if(ValidationHelper.isEmptyOrNullString(jStatus.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Status cannot be null.");
                return;
            }
            
            Map<String, String> idsMap = Stream.of(new String[][] {
                                    { "Precinct ID",  jCaseId.getText()}
                                }).collect(Collectors.toMap(data -> data[0], data -> data[1]));
        
            String invalidId = ValidationHelper.getInvalidNumericId(idsMap);
        
            if (!invalidId.isBlank()) {
                JOptionPane.showMessageDialog(this, "Please Enter a Valid Numeric " + invalidId);
                return;
            }
        
        DefaultTableModel tblModel = (DefaultTableModel)jBackgroundTable.getModel();
        
        if (jBackgroundTable.getSelectedRowCount() == 1){

            Integer statusId = Integer.valueOf(tblModel.getValueAt(jBackgroundTable.getSelectedRow(), 0).toString());
          
            
            String desc = jWantedLevel.getSelectedItem().toString();
            String status = jStatus.getSelectedItem().toString(); 
            
            tblModel.setValueAt(status, jBackgroundTable.getSelectedRow(), 2);
            tblModel.setValueAt(status, jBackgroundTable.getSelectedRow(), 4);
            
          
            Map<String, String> mp = new HashMap<>();
            mp.put("wantedlevel", desc);
            mp.put("status", status);
            
            try {
                Helper.updateColumns("citizen_status", mp, "status_id = " + statusId);
            }
            catch (SQLException ex) {
                System.out.println("Failed");
                Logger.getLogger(CasePortalCaptain.class.getName()).log(Level.SEVERE, null, ex);
            }

            tblModel.setRowCount(0);

//            try {
//                    List<Evidence> evidenceList = null;
//                    if(currentCaseId != null) {
//                        evidenceList = Helper.getResultSetByConditionId(Evidence.class, "evidence", "case_id", currentCaseId);
//                    } else {
//                       evidenceList = Helper.getResultSet(Evidence.class, "evidence"); 
//                    }
//                    if(evidenceList != null) {
//                        for(Evidence i : evidenceList){
//                            Integer evId = i.getEvidenceId();
//                            Integer casId = i.getCaseId();
//                            String objDesc = i.getDescription();
//                            Object[] obj = {evId, casId, objDesc};
//                            tblModel.addRow(obj);   
//                        }
//                }
//            } catch (InstantiationException ex) {
//                Logger.getLogger(CasePortalCaptain.class.getName()).log(Level.SEVERE, null, ex);
//            }
        }
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void createEvidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEvidenceActionPerformed
        try {
            if(ValidationHelper.isEmptyOrNullString(jCaseId.getText())) {
                JOptionPane.showMessageDialog(this, "Case ID cannot be null.");
                return;
            }
            
            if(ValidationHelper.isEmptyOrNullString(jWantedLevel.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Wanted Level cannot be null.");
                return;
            }
            
            if(ValidationHelper.isEmptyOrNullString(jStatus.getSelectedItem().toString())) {
                JOptionPane.showMessageDialog(this, "Status cannot be null.");
                return;
            }
            
            Map<String, String> idsMap = Stream.of(new String[][] {
                                    { "Precinct ID",  jCaseId.getText()}
                                }).collect(Collectors.toMap(data -> data[0], data -> data[1]));
        
            String invalidId = ValidationHelper.getInvalidNumericId(idsMap);
        
            if (!invalidId.isBlank()) {
                JOptionPane.showMessageDialog(this, "Please Enter a Valid Numeric " + invalidId);
                return;
            }
            
            Integer caseId = Integer.parseInt(jCaseId.getText());
            Integer wantedLevel = Integer.parseInt(jWantedLevel.getSelectedItem().toString());
            String status = jStatus.getSelectedItem().toString().toString();
            Integer personId = CurrentSession.queryUser;
            
            Integer statusId = Helper.getMaxId("citizen_status", "citizen",null);
            
            Person person = Helper.fetchPerson(personId);            
            String name = person.getName();
            
            DefaultTableModel tblModel = (DefaultTableModel)jBackgroundTable.getModel();
            Object [] obj = {statusId, name, status, caseId, wantedLevel};
            tblModel.addRow(obj);
            
            CitizenStatus cs = new CitizenStatus(statusId, person, personId, status, caseId, wantedLevel);
            cs.addToCitizenStatus(cs);
                    
                    } catch (SQLException ex) {
            Logger.getLogger(CitizenStatusPortal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(CitizenStatusPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_createEvidenceActionPerformed

    public void resetAllFields() {
//        jEvidenceId.setText(null);
//        jCaseId.setText("");
//        jWantedLevel.setText("");
//        imageLabel.setIcon(null);
    }
    
    private void jBackgroundTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBackgroundTableMouseClicked
        
        resetAllFields();
        DefaultTableModel tblModel = (DefaultTableModel)jBackgroundTable.getModel(); 
        jCaseId.setText(tblModel.getValueAt(jBackgroundTable.getSelectedRow(), 3).toString());
        
    }//GEN-LAST:event_jBackgroundTableMouseClicked

    private void jCaseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCaseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCaseIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try { 
            BackgroundCheckDetective obj = new BackgroundCheckDetective();
            obj.setVisible(true);
            obj.setExtendedState(JFrame.MAXIMIZED_BOTH );
            dispose();
        } catch (InstantiationException ex) {
            Logger.getLogger(CitizenStatusPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CitizenStatusPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CitizenStatusPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CitizenStatusPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CitizenStatusPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CitizenStatusPortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEvidence;
    private javax.swing.JTable jBackgroundTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCaseId;
    private javax.swing.JLabel jImagePath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jStatus;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JComboBox<String> jWantedLevel;
    // End of variables declaration//GEN-END:variables
}
