/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PoliceDepartment;

/**
 *
 * @author sahilpadyal
 */

import crimepatrolfinalproject.Login;
import java.awt.Image;
import java.io.File;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import utilPackage.Helper;
import utilPackage.S3BucketOperations;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.Evidence;
import utilPackage.ResultSetMapper;
import utilPackage.ValidationHelper;
public class EvidencePortal extends javax.swing.JFrame {

    /**
     * Creates new form mainPoliceDept
     */
    Integer currentCaseId;
    public EvidencePortal() {
        initComponents();
        
        jEvidenceId.disable();
        
        try {
          
            List<Evidence> evidenceList = Helper.getResultSet(Evidence.class, "evidence");
            
            if(evidenceList != null) {
                for(Evidence i : evidenceList){
                    Integer evidenceId = i.getEvidenceId();
                    Integer caseId = i.getCaseId();
                    String description = i.getDescription();
                    DefaultTableModel tblModel = (DefaultTableModel)jEvidenceTable.getModel();
                    Object[] obj = {evidenceId, caseId, description};
                    tblModel.addRow(obj);                   
                }
            }
            
            
        } catch (InstantiationException ex) {
            Logger.getLogger(CasePortalCaptain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public EvidencePortal(Integer currCaseId) {
        initComponents();
        
        jEvidenceId.disable();
        
        currentCaseId = currCaseId;
        
        System.out.println("current case id ===> " + currentCaseId);
        
        try {
          
            
            List<Evidence> evidenceList = Helper.getResultSetByConditionId(Evidence.class, "evidence","case_id", currentCaseId);
            
            if(evidenceList != null) {
                for(Evidence i : evidenceList){
                    Integer evidenceId = i.getEvidenceId();
                    Integer caseId = i.getCaseId();
                    String description = i.getDescription();
                    DefaultTableModel tblModel = (DefaultTableModel)jEvidenceTable.getModel();
                    Object[] obj = {evidenceId, caseId, description};
                    tblModel.addRow(obj);                   
                }
                
                Evidence ev1 = evidenceList.get(0);
                jEvidenceId.setText(ev1.getEvidenceId().toString());
                jCaseId.setText(ev1.getCaseId().toString());
                jDescription.setText(ev1.getDescription());
                jImagePath.setName(ev1.getImagePath());
                ImageIcon imgIcon = new ImageIcon(ev1.getImagePath());
                Image img = imgIcon.getImage();
                Image scaledImage = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledImgIcon = new ImageIcon(scaledImage);
                imageLabel.setIcon(scaledImgIcon);
            }
            
            
            
            
        } catch (InstantiationException ex) {
            Logger.getLogger(CasePortalCaptain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uploadEvidence = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEvidenceTable = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jDelete = new javax.swing.JButton();
        jUpdateButton = new javax.swing.JButton();
        createEvidence = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jImagePath = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jEvidenceId = new javax.swing.JTextField();
        jDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCaseId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 278, 270, -1));

        uploadEvidence.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        uploadEvidence.setForeground(new java.awt.Color(51, 102, 0));
        uploadEvidence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/reception.png"))); // NOI18N
        uploadEvidence.setText("Upload/Replace Evidence");
        uploadEvidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadEvidenceActionPerformed(evt);
            }
        });
        getContentPane().add(uploadEvidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 302, -1, -1));
        getContentPane().add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 142, 123, 142));

        jEvidenceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evidence ID", "Case ID", "Description"
            }
        ));
        jEvidenceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jEvidenceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jEvidenceTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 872, 236));

        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 102, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/delete (1).png"))); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(862, 302, -1, 54));

        jDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jDelete.setForeground(new java.awt.Color(51, 102, 0));
        jDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/deletepatient.png"))); // NOI18N
        jDelete.setText("Delete");
        jDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(jDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(729, 302, -1, -1));

        jUpdateButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jUpdateButton.setForeground(new java.awt.Color(51, 102, 0));
        jUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/updatepatient.png"))); // NOI18N
        jUpdateButton.setText("Update");
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(jUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 302, -1, -1));

        createEvidence.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        createEvidence.setForeground(new java.awt.Color(51, 102, 0));
        createEvidence.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/addpatient.png"))); // NOI18N
        createEvidence.setText("Create");
        createEvidence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEvidenceActionPerformed(evt);
            }
        });
        getContentPane().add(createEvidence, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 302, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 365, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 244, -1, 40));
        getContentPane().add(jImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 284, 42, 48));

        jLabel1.setFont(new java.awt.Font("Helvetica", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Evidence Portal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 72, 388, 95));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 0));
        jLabel2.setText("Case ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 190, 64, -1));

        jEvidenceId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEvidenceIdActionPerformed(evt);
            }
        });
        getContentPane().add(jEvidenceId, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 146, 143, -1));
        getContentPane().add(jDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 230, 144, 54));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 102, 0));
        jLabel3.setText("Description");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 248, 75, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 0));
        jLabel6.setText("Evidence ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 149, 82, -1));

        jCaseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCaseIdActionPerformed(evt);
            }
        });
        getContentPane().add(jCaseId, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 187, 143, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/search.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(232, 72, 151, -1));

        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 102, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/cross.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(731, 6, -1, -1));

        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 102, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/backs.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadEvidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadEvidenceActionPerformed
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGE", "png","jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOptionDialogue = browseImageFile.showOpenDialog(null);
        if(showOptionDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            ImageIcon imgIcon = new ImageIcon(selectedImagePath);
            Image img = imgIcon.getImage();
            Image scaledImage = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledImgIcon = new ImageIcon(scaledImage);
            imageLabel.setIcon(scaledImgIcon);
            S3BucketOperations.uploadS3Object(selectedImagePath);
            jImagePath.setName(selectedImagePath);
        }
    }//GEN-LAST:event_uploadEvidenceActionPerformed

    private void jEvidenceIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEvidenceIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEvidenceIdActionPerformed

    private void jDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteActionPerformed

        DefaultTableModel tblModel = (DefaultTableModel)jEvidenceTable.getModel();
        if(jEvidenceTable.getSelectedRowCount() == 1){
            Integer evidenceId = Integer.valueOf(tblModel.getValueAt(jEvidenceTable.getSelectedRow(), 1).toString());
            tblModel.removeRow(jEvidenceTable.getSelectedRow());
            Helper.insertDeleteData("delete from evidence where evidence_id = " + evidenceId);
            resetAllFields();
        }

    }//GEN-LAST:event_jDeleteActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        
        if(ValidationHelper.isEmptyOrNullString(jCaseId.getText())) {
                JOptionPane.showMessageDialog(this, "Case ID cannot be null.");
                return;
        }
            
        Map<String, String> idsMap = Stream.of(new String[][] {
                                { "Case ID",  jCaseId.getText()}
                            }).collect(Collectors.toMap(data -> data[0], data -> data[1]));

        String invalidId = ValidationHelper.getInvalidNumericId(idsMap);

        if (!invalidId.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Numeric " + invalidId);
            return;
        }
        
        DefaultTableModel tblModel = (DefaultTableModel)jEvidenceTable.getModel();
        
        if (jEvidenceTable.getSelectedRowCount() == 1){

            Integer caseId = Integer.valueOf(tblModel.getValueAt(jEvidenceTable.getSelectedRow(), 1).toString());
            if(caseId != Integer.parseInt(jCaseId.getText())) {
                JOptionPane.showMessageDialog(this, "Case ID for an Evidence cannot be updated.");
                return;
            }
            
            String desc = jDescription.getText();
            String imagePath = jImagePath.getName();
            
            Integer evidenceId = Integer.valueOf(jEvidenceId.getText());
            
            Map<String, String> mp = new HashMap<>();
            mp.put("description", desc);
            mp.put("IMAGEPATH", imagePath);
            
            try {
                Helper.updateColumns("evidence", mp, "evidence_id = " + evidenceId);
            }
            catch (SQLException ex) {
                System.out.println("Failed");
                Logger.getLogger(CasePortalCaptain.class.getName()).log(Level.SEVERE, null, ex);
            }

            tblModel.setRowCount(0);

            try {
                    List<Evidence> evidenceList = null;
                    if(currentCaseId != null) {
                        evidenceList = Helper.getResultSetByConditionId(Evidence.class, "evidence", "case_id", currentCaseId);
                    } else {
                       evidenceList = Helper.getResultSet(Evidence.class, "evidence"); 
                    }
                    if(evidenceList != null) {
                        for(Evidence i : evidenceList){
                            Integer evId = i.getEvidenceId();
                            Integer casId = i.getCaseId();
                            String objDesc = i.getDescription();
                            Object[] obj = {evId, casId, objDesc};
                            tblModel.addRow(obj);   
                        }
                }
            } catch (InstantiationException ex) {
                Logger.getLogger(CasePortalCaptain.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jUpdateButtonActionPerformed

    private void createEvidenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEvidenceActionPerformed

        if(ValidationHelper.isEmptyOrNullString(jCaseId.getText())) {
                JOptionPane.showMessageDialog(this, "Case ID cannot be null.");
                return;
        }
            
        Map<String, String> idsMap = Stream.of(new String[][] {
                                { "Case ID",  jCaseId.getText()}
                            }).collect(Collectors.toMap(data -> data[0], data -> data[1]));

        String invalidId = ValidationHelper.getInvalidNumericId(idsMap);

        if (!invalidId.isBlank()) {
            JOptionPane.showMessageDialog(this, "Please Enter a Valid Numeric " + invalidId);
            return;
        }
        
        Integer caseId = Integer.parseInt(jCaseId.getText());
        String desc = jDescription.getText();
        String imagePath = jImagePath.getName();

        Integer evidenceId = null;
        try {
            evidenceId = Helper.getMaxId("evidence", "evidence_id", null);
        } catch (SQLException ex) {
            Logger.getLogger(EvidencePortal.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel tblModel = (DefaultTableModel)jEvidenceTable.getModel();
        Object[] obj = {evidenceId, caseId, desc};
        tblModel.addRow(obj);

        Evidence evidence = new Evidence(evidenceId, caseId, desc, imagePath);
        evidence.addToEvidenceTable(evidence);
        resetAllFields();

    }//GEN-LAST:event_createEvidenceActionPerformed

    public void resetAllFields() {
        jEvidenceId.setText(null);
        jCaseId.setText("");
        jDescription.setText("");
        imageLabel.setIcon(null);
    }
    
    private void jEvidenceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEvidenceTableMouseClicked
        // TODO add your handling code here:
        resetAllFields();
        DefaultTableModel tblModel = (DefaultTableModel)jEvidenceTable.getModel(); 
        if(jEvidenceTable.getSelectedRowCount() == 1){
            
            Integer evidenceId = Integer.parseInt(tblModel.getValueAt(jEvidenceTable.getSelectedRow(), 0).toString());
            jDescription.setText(tblModel.getValueAt(jEvidenceTable.getSelectedRow(), 2).toString());
            jCaseId.setText(tblModel.getValueAt(jEvidenceTable.getSelectedRow(), 1).toString());
            jEvidenceId.setText(tblModel.getValueAt(jEvidenceTable.getSelectedRow(), 0).toString());
            
            List<Evidence> evidenceList = new ArrayList<>();
            try {
                evidenceList = Helper.getResultSetByConditionId(Evidence.class, "evidence", "evidence_id", evidenceId);
            } catch (InstantiationException ex) {
                Logger.getLogger(EvidencePortal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            if(evidenceList.size() == 1 && evidenceList.get(0).getImagePath() != null) {
                jImagePath.setName(evidenceList.get(0).getImagePath());
                ImageIcon imgIcon = new ImageIcon(evidenceList.get(0).getImagePath());
                Image img = imgIcon.getImage();
                Image scaledImage = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), Image.SCALE_SMOOTH);
                ImageIcon scaledImgIcon = new ImageIcon(scaledImage);
                imageLabel.setIcon(scaledImgIcon);
            }
            
        }
    }//GEN-LAST:event_jEvidenceTableMouseClicked

    private void jCaseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCaseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCaseIdActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        resetAllFields();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login obj = new Login();
        obj.setVisible(true);
        obj.setExtendedState(JFrame.MAXIMIZED_BOTH );
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CaptainMenu obj = new CaptainMenu();
        obj.setVisible(true);
        obj.setExtendedState(JFrame.MAXIMIZED_BOTH );
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvidencePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvidencePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvidencePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvidencePortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvidencePortal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createEvidence;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JTextField jCaseId;
    private javax.swing.JButton jDelete;
    private javax.swing.JTextField jDescription;
    private javax.swing.JTextField jEvidenceId;
    private javax.swing.JTable jEvidenceTable;
    private javax.swing.JLabel jImagePath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JButton uploadEvidence;
    // End of variables declaration//GEN-END:variables
}
