/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MedicalDepartment;

import crimepatrolfinalproject.SysAdminJFrame1;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Hospital;
import model.Person;
import utilPackage.CurrentSession;
import utilPackage.Helper;

/**
 *
 * @author bashu
 */
public class DoctorProfile extends javax.swing.JFrame {

    /**
     * Creates new form DoctorProfile
     */
    public DoctorProfile() {
        initComponents();
        
        Integer doctorId = CurrentSession.getCurrentUser().getId();

        Integer hospitalId = null;
        String hospitalName = null;
        Person person = null;
            
        try {
            hospitalId = Helper.fetchHospitalIdForDoctor(doctorId);
            Hospital hospital = Helper.fetchHospital(hospitalId);
            hospitalName = hospital.getName();
            person = Helper.fetchPerson(doctorId);
        } catch (SQLException ex) {
            Logger.getLogger(DoctorProfile.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(DoctorProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        jDocName.setText(person.getName());
        hospitalIdTextField.setText(hospitalId.toString());
        jAddress.setText(person.getAddress().toString());
        jEmail.setText(person.getEmail());
        jPhone.setText(person.getPhoneNo().toString());
        jBloodGroup.setText(person.getBloodGroup());
        jGender.setSelectedItem(person.getGender());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hospitalIdTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        hospitalNameTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPhone = new javax.swing.JTextField();
        jGender = new javax.swing.JComboBox<>();
        jDocName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBloodGroup = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jAddress = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jEmail = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        doctorId = new javax.swing.JTextField();
        hospUpdateBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        homePageBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(hospitalIdTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 151, 151, -1));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 255));
        jLabel7.setText("Hospital Id");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 154, 100, -1));
        getContentPane().add(hospitalNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 192, 151, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 255));
        jLabel1.setText("Hospital Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 195, 100, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel8.setText("Doctor Profile");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 118, -1, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel9.setText("Hospital Details");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 118, -1, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Doctor Details");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 31, -1, -1));

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 204, 255));
        jLabel15.setText("Doctor Id");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 154, 100, -1));
        getContentPane().add(jPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 268, 151, -1));

        jGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(jGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 385, 151, -1));
        getContentPane().add(jDocName, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 192, 151, -1));

        jLabel16.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 204, 255));
        jLabel16.setText("Phone Number");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 271, -1, -1));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 204, 255));
        jLabel13.setText("Gender");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 388, -1, -1));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Doctor Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 195, 100, -1));
        getContentPane().add(jBloodGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 344, 151, -1));

        jLabel17.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 204, 255));
        jLabel17.setText("Blood Group");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 350, -1, -1));
        getContentPane().add(jAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 309, 151, -1));

        jLabel18.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 255));
        jLabel18.setText("Address");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 312, -1, -1));
        getContentPane().add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 233, 151, -1));

        jLabel19.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 255));
        jLabel19.setText("Email");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 236, 100, -1));
        getContentPane().add(doctorId, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 151, 151, -1));

        hospUpdateBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        hospUpdateBtn.setForeground(new java.awt.Color(0, 204, 255));
        hospUpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/updatepatient.png"))); // NOI18N
        hospUpdateBtn.setText("UPDATE");
        hospUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospUpdateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(hospUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 464, -1, -1));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/admin.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 24, 127, -1));

        homePageBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        homePageBtn1.setForeground(new java.awt.Color(0, 204, 255));
        homePageBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/backs.png"))); // NOI18N
        homePageBtn1.setText("BACK");
        homePageBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(homePageBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, 38));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hospUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospUpdateBtnActionPerformed
        // TODO add your handling code here:
       
        Integer doctorId = CurrentSession.getCurrentUser().getId();

//        Integer hospitalId = null;
//        String hospitalName = null;
//        Person person = null;
//            
//        try {
//            hospitalId = Helper.fetchHospitalIdForDoctor(doctorId);
//            Hospital hospital = Helper.fetchHospital(hospitalId);
//            hospitalName = hospital.getName();
//            person = Helper.fetchPerson(doctorId);
//        } catch (SQLException ex) {
//            Logger.getLogger(DoctorProfile.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (ParseException ex) {
//            Logger.getLogger(DoctorProfile.class.getName()).log(Level.SEVERE, null, ex);
//        }
            
            String docName = jDocName.getText();
//            Integer hospitalId = Integer.parseInt(hospitalIdTextField.getText());
            Integer locationId = Integer.parseInt(jAddress.getText());
            String email = jEmail.getText();
            Integer phone = Integer.parseInt(jPhone.getText());
            String bloodGroup = jBloodGroup.getText();
            String gender = jGender.getSelectedItem().toString();

            Map<String, String> personUpdMap = new HashMap<>();
            personUpdMap.put("name", String.valueOf(docName));
            personUpdMap.put("location_id", String.valueOf(locationId));
            personUpdMap.put("email", String.valueOf(email));
            personUpdMap.put("phone_no", String.valueOf(phone));
            personUpdMap.put("blood_group", String.valueOf(bloodGroup));
            personUpdMap.put("gender", String.valueOf(gender));

//            Map<String, String> doctorUpdMap = new HashMap<>();
//            doctorUpdMap.put("hospital_id", String.valueOf(hospitalId));
        try {
            Helper.updateColumns("person", personUpdMap, "person_id = " + doctorId);
            JOptionPane.showMessageDialog(this, "Doctor Details Updated Successfully!!!");
//                Helper.updateColumns("doctor", doctorUpdMap, "doctor_id = " + doctorId);
        } catch (SQLException ex) {
            Logger.getLogger(DoctorProfile.class.getName()).log(Level.SEVERE, null, ex);
        }
            

    }//GEN-LAST:event_hospUpdateBtnActionPerformed

    private void homePageBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageBtn1ActionPerformed

        SysAdminJFrame1 obj = new SysAdminJFrame1();
        obj.setVisible(true);
        obj.setExtendedState(JFrame.MAXIMIZED_BOTH );
        dispose();

    }//GEN-LAST:event_homePageBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoctorProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoctorProfile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField doctorId;
    private javax.swing.JButton homePageBtn1;
    private javax.swing.JButton hospUpdateBtn;
    private javax.swing.JTextField hospitalIdTextField;
    private javax.swing.JTextField hospitalNameTextField;
    private javax.swing.JTextField jAddress;
    private javax.swing.JTextField jBloodGroup;
    private javax.swing.JTextField jDocName;
    private javax.swing.JTextField jEmail;
    private javax.swing.JComboBox<String> jGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jPhone;
    // End of variables declaration//GEN-END:variables
}
