/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FireDepartment;

import MedicalDepartment.*;
import PoliceDepartment.Case;
import PoliceDepartment.Precinct;
import crimepatrolfinalproject.SysAdminJFrame1;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Hospital;
import model.Location;
import utilPackage.Helper;
import utilPackage.SendNotification;
import utilPackage.ValidationHelper;

/**
 *
 * @author bashu
 */
public class FireStationPortal extends javax.swing.JFrame {

    /**
     * Creates new form HospitalJFrame
     */
    public FireStationPortal() {
        initComponents();
//        stationIdTextField.disable();
        try {
          
            List<FireStation> objList = Helper.getResultSet(FireStation.class, "firestation");
            
            for(FireStation i : objList){
                Integer iD = i.getStationId();
                
                Integer locationId = i.getLocationId();
                String email = i.getEmail(); 
                
                DefaultTableModel tblModel = (DefaultTableModel)fireStationJTable.getModel();
                Object[] obj = {iD,locationId, email};
                tblModel.addRow(obj);                   
            }
            
        } catch (InstantiationException ex) {
            Logger.getLogger(FireStationPortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        fireStationJTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        homePageBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fireStationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Station ID", "Location ID", "Email"
            }
        ));
        fireStationJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireStationJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fireStationJTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 770, 290));

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fire Station Portal");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 37, -1, -1));

        homePageBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        homePageBtn1.setForeground(new java.awt.Color(0, 204, 255));
        homePageBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/backs.png"))); // NOI18N
        homePageBtn1.setText("BACK");
        homePageBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(homePageBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 140, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fireStationJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireStationJTableMouseClicked
        // TODO add your handling code here:
              
        DefaultTableModel fireTableModel = (DefaultTableModel) fireStationJTable.getModel();
        
        if(fireStationJTable.getSelectedRowCount() == 1) {
            
            String tblHospId = fireTableModel.getValueAt( fireStationJTable.getSelectedRow(),0).toString();
            //String tblHospName = hospTableModel.getValueAt( fireStationJTable.getSelectedRow(),1).toString();
            String tblHospLocationId = fireTableModel.getValueAt( fireStationJTable.getSelectedRow(),1).toString();
            String tblHospEmail = "";
            if(fireTableModel.getValueAt( fireStationJTable.getSelectedRow(),2) != null) {
               tblHospEmail = fireTableModel.getValueAt( fireStationJTable.getSelectedRow(),2).toString(); 
            }
            
            //String tblHospContact = hospTableModel.getValueAt( fireStationJTable.getSelectedRow(),4).toString();


//            stationIdTextField.setText(tblHospId);
//            //stationNameTextField.setText(tblHospName);
//            jLocationId.setText(tblHospLocationId);
//            jEmailId.setText(tblHospEmail);
            //jContactNum.setText(tblHospContact);
        }
        
        
    }//GEN-LAST:event_fireStationJTableMouseClicked

    public void resetAllFields() {
//        stationIdTextField.setText(null);
//     //   stationNameTextField.setText(null);
//        jLocationId.setText(null);
//        jEmailId.setText(null);
    //    jContactNum.setText(null);
    }
    
    private void homePageBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageBtn1ActionPerformed

        SysAdminJFrame1 obj = new SysAdminJFrame1();
        obj.setVisible(true);
        obj.setExtendedState(JFrame.MAXIMIZED_BOTH );
        dispose();

    }//GEN-LAST:event_homePageBtn1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FireStationPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FireStationPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FireStationPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FireStationPortal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FireStationPortal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable fireStationJTable;
    private javax.swing.JButton homePageBtn1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
