/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FireDepartment;

import MedicalDepartment.*;
import PoliceDepartment.Case;
import PoliceDepartment.CasePortal;
import PoliceDepartment.Precinct;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Hospital;
import model.Location;
import utilPackage.Helper;
import utilPackage.SendNotification;

/**
 *
 * @author bashu
 */
public class FireStationPortalSysAdmin extends javax.swing.JFrame {

    /**
     * Creates new form HospitalJFrame
     */
    public FireStationPortalSysAdmin() {
        initComponents();
        stationIdTextField.disable();
        try {
          
            List<FireStation> objList = Helper.getResultSet(FireStation.class, "firestation");
            
            for(FireStation i : objList){
                Integer iD = i.getStationId();
                
                Integer locationId = i.getLocationId();
                String email = i.getEmail(); 
                
                DefaultTableModel tblModel = (DefaultTableModel)fireStationJTable.getModel();
                Object[] obj = {iD,locationId, email};
                tblModel.addRow(obj);                   
            }
            
        } catch (InstantiationException ex) {
            Logger.getLogger(CasePortal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLocationId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jEmailId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        fireStationJTable = new javax.swing.JTable();
        fireCreateBtn = new javax.swing.JButton();
        fireUpdateBtn = new javax.swing.JButton();
        hospDeleteBtn = new javax.swing.JButton();
        hospResetBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        stationIdTextField = new javax.swing.JTextField();
        homePageBtn = new javax.swing.JButton();
        homePageBtn1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        hospResetBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Location ID");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Email");

        jEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEmailIdActionPerformed(evt);
            }
        });

        fireStationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Station ID", "Location ID", "Email"
            }
        ));
        fireStationJTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fireStationJTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(fireStationJTable);

        fireCreateBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        fireCreateBtn.setForeground(new java.awt.Color(255, 51, 51));
        fireCreateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/addpatient.png"))); // NOI18N
        fireCreateBtn.setText("CREATE");
        fireCreateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireCreateBtnActionPerformed(evt);
            }
        });

        fireUpdateBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        fireUpdateBtn.setForeground(new java.awt.Color(255, 51, 51));
        fireUpdateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/updatepatient.png"))); // NOI18N
        fireUpdateBtn.setText("UPDATE");
        fireUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fireUpdateBtnActionPerformed(evt);
            }
        });

        hospDeleteBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        hospDeleteBtn.setForeground(new java.awt.Color(255, 51, 51));
        hospDeleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/deletepatient.png"))); // NOI18N
        hospDeleteBtn.setText("DELETE");
        hospDeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospDeleteBtnActionPerformed(evt);
            }
        });

        hospResetBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        hospResetBtn.setForeground(new java.awt.Color(255, 0, 0));
        hospResetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/cross.png"))); // NOI18N
        hospResetBtn.setText("RESET");
        hospResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospResetBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Station Id");

        homePageBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        homePageBtn.setForeground(new java.awt.Color(255, 0, 0));
        homePageBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/Home.png"))); // NOI18N
        homePageBtn.setText("HOME");
        homePageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageBtnActionPerformed(evt);
            }
        });

        homePageBtn1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        homePageBtn1.setForeground(new java.awt.Color(255, 51, 51));
        homePageBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/backs.png"))); // NOI18N
        homePageBtn1.setText("BACK");
        homePageBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageBtn1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Helvetica", 1, 40)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Fire Station Management Portal");

        hospResetBtn1.setText("VIEW CASE");
        hospResetBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospResetBtn1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon2/Fire.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stationIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLocationId, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fireCreateBtn)
                            .addComponent(hospDeleteBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fireUpdateBtn)
                            .addComponent(hospResetBtn))
                        .addGap(44, 44, 44)))
                .addComponent(jScrollPane1)
                .addGap(89, 89, 89))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hospResetBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homePageBtn)
                .addGap(27, 27, 27)
                .addComponent(homePageBtn1)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homePageBtn)
                    .addComponent(homePageBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(stationIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLocationId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fireCreateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fireUpdateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hospDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hospResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(51, 51, 51)
                .addComponent(hospResetBtn1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fireCreateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireCreateBtnActionPerformed
        // TODO add your handling code here:
        
        Integer locationId = Integer.parseInt(jLocationId.getText());
        String email = jEmailId.getText();
        
        Integer firestationId = 0;
        try {
            firestationId = Helper.getMaxId("firestation", "station_id", null);
        } catch (SQLException ex) {
            Logger.getLogger(CasePortal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        DefaultTableModel tblModel = (DefaultTableModel)fireStationJTable.getModel();
        Object[] obj = {firestationId,locationId, email};
        tblModel.addRow(obj);
       
        Location loc = null;
        FireStation firestation = new FireStation(firestationId,  locationId, email);
        firestation.InsertToFireTable(firestation);
        JOptionPane.showMessageDialog(this, "Station Saved Successfully!!!");
    }//GEN-LAST:event_fireCreateBtnActionPerformed

    private void fireStationJTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fireStationJTableMouseClicked
        // TODO add your handling code here:
              
        DefaultTableModel fireTableModel = (DefaultTableModel) fireStationJTable.getModel();
        
        if(fireStationJTable.getSelectedRowCount() == 1) {
            
            String tblHospId = fireTableModel.getValueAt( fireStationJTable.getSelectedRow(),0).toString();
            //String tblHospName = hospTableModel.getValueAt( fireStationJTable.getSelectedRow(),1).toString();
            String tblHospLocationId = fireTableModel.getValueAt( fireStationJTable.getSelectedRow(),1).toString();
            String tblHospEmail = fireTableModel.getValueAt( fireStationJTable.getSelectedRow(),2).toString();
            //String tblHospContact = hospTableModel.getValueAt( fireStationJTable.getSelectedRow(),4).toString();


            stationIdTextField.setText(tblHospId);
            //stationNameTextField.setText(tblHospName);
            jLocationId.setText(tblHospLocationId);
            jEmailId.setText(tblHospEmail);
            //jContactNum.setText(tblHospContact);
        }
        
        
    }//GEN-LAST:event_fireStationJTableMouseClicked

    private void fireUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fireUpdateBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)fireStationJTable.getModel();
        
        
        if (fireStationJTable.getSelectedRowCount() == 1){
            
            Integer stationId = Integer.valueOf(tblModel.getValueAt(fireStationJTable.getSelectedRow(), 0).toString()); 
            //String hospitalName = stationNameTextField.getText(); 
            Integer loccationId = Integer.valueOf(jLocationId.getText()); 
            String email = jEmailId.getText();
            //Integer contactNum = Integer.valueOf(jContactNum.getText()); 
            
           
            
            tblModel.setValueAt(loccationId, fireStationJTable.getSelectedRow(), 2);
            tblModel.setValueAt(email, fireStationJTable.getSelectedRow(), 3);
            
            
            Map<String, String> mp = new HashMap<>();
            //mp.put("name", String.valueOf(hospitalName));
            mp.put("locationid", String.valueOf(loccationId));
            mp.put("email", String.valueOf(email));
            //mp.put("contactno", String.valueOf(contactNum));
            
            try {
                Helper.updateColumns("firestation", mp, "station_id = " + stationId);
            } 
            
            catch (SQLException ex) {
                System.out.println("Failed");
                Logger.getLogger(CasePortal.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            tblModel.setRowCount(0);
            
            try {
          
            List<FireStation> objList = Helper.getResultSet(FireStation.class, "firestation");
            
            for(FireStation i : objList){
                Integer iD = i.getStationId();
                //String name = i.getName();
                Integer locationId = i.getLocationId();
                String emailId = i.getEmail(); 
                //Integer contactNo = i.getContactNum(); 
                Object[] obj = {iD,locationId, emailId,};
                tblModel.addRow(obj);                   
            }
            
        } catch (InstantiationException ex) {
            Logger.getLogger(CasePortal.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        }
        
    }//GEN-LAST:event_fireUpdateBtnActionPerformed

    private void hospDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospDeleteBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tblModel = (DefaultTableModel)fireStationJTable.getModel();
        if(fireStationJTable.getSelectedRowCount() == 1){
            
            Integer firestationId = Integer.valueOf(tblModel.getValueAt(fireStationJTable.getSelectedRow(), 0).toString()); 
            tblModel.removeRow(fireStationJTable.getSelectedRow());
            
            Helper.insertDeleteData("delete from firestation where station_id = " + firestationId);
            
          }
       
        
    }//GEN-LAST:event_hospDeleteBtnActionPerformed

    public void resetAllFields() {
        stationIdTextField.setText(null);
     //   stationNameTextField.setText(null);
        jLocationId.setText(null);
        jEmailId.setText(null);
    //    jContactNum.setText(null);
    }
    
    private void hospResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospResetBtnActionPerformed
        // TODO add your handling code here:
        resetAllFields();
    }//GEN-LAST:event_hospResetBtnActionPerformed

    private void homePageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_homePageBtnActionPerformed

    private void homePageBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homePageBtn1ActionPerformed

    private void jEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jEmailIdActionPerformed

    private void hospResetBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospResetBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hospResetBtn1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FireStationPortalSysAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FireStationPortalSysAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FireStationPortalSysAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FireStationPortalSysAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FireStationPortalSysAdmin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fireCreateBtn;
    private javax.swing.JTable fireStationJTable;
    private javax.swing.JButton fireUpdateBtn;
    private javax.swing.JButton homePageBtn;
    private javax.swing.JButton homePageBtn1;
    private javax.swing.JButton hospDeleteBtn;
    private javax.swing.JButton hospResetBtn;
    private javax.swing.JButton hospResetBtn1;
    private javax.swing.JTextField jEmailId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jLocationId;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField stationIdTextField;
    // End of variables declaration//GEN-END:variables
}
