/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package crimepatrolfinalproject;

import LegalDepartment.LegalDeptAdmin;
import MedicalDepartment.DoctorManagementPortal;
import MedicalDepartment.HospitalPortal;
import PoliceDepartment.PoliceAdminActivity;
import citizenApp.CitizenMenu;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bashu
 */
public class SysAdminJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form SysAdminJFrame
     */
    public SysAdminJFrame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageHospitalBtn = new javax.swing.JButton();
        manageCommAdminsBtn = new javax.swing.JButton();
        manageFireStationBtn = new javax.swing.JButton();
        managePoliceBtn = new javax.swing.JButton();
        manageHospitalsBtn = new javax.swing.JButton();
        manageEncountersBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        homePageBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageHospitalBtn.setText("MANAGE HOSPITALS");
        manageHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHospitalBtnActionPerformed(evt);
            }
        });

        manageCommAdminsBtn.setText("MANAGE LAWYERS");
        manageCommAdminsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCommAdminsBtnActionPerformed(evt);
            }
        });

        manageFireStationBtn.setText("MANAGE FIRE STATION");
        manageFireStationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageFireStationBtnActionPerformed(evt);
            }
        });

        managePoliceBtn.setText("MANAGE POLICE");
        managePoliceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePoliceBtnActionPerformed(evt);
            }
        });

        manageHospitalsBtn.setText("MANAGE CITIZENS");
        manageHospitalsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageHospitalsBtnActionPerformed(evt);
            }
        });

        manageEncountersBtn.setText("MANAGE DOCTORS");
        manageEncountersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageEncountersBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("SYSTEM ADMIN OPERATIONS");

        homePageBtn.setText("HOME");
        homePageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(homePageBtn)
                        .addGap(99, 99, 99))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(manageEncountersBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(managePoliceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageHospitalBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageHospitalsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageCommAdminsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(manageFireStationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(homePageBtn))
                .addGap(76, 76, 76)
                .addComponent(manageHospitalBtn)
                .addGap(18, 18, 18)
                .addComponent(managePoliceBtn)
                .addGap(18, 18, 18)
                .addComponent(manageFireStationBtn)
                .addGap(18, 18, 18)
                .addComponent(manageCommAdminsBtn)
                .addGap(18, 18, 18)
                .addComponent(manageHospitalsBtn)
                .addGap(18, 18, 18)
                .addComponent(manageEncountersBtn)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHospitalBtnActionPerformed
        // TODO add your handling code here:
        HospitalPortal hp = new HospitalPortal();
        hp.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageHospitalBtnActionPerformed

    private void manageHospitalsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageHospitalsBtnActionPerformed
        // TODO add your handling code here:
        CitizenMenu cm = new CitizenMenu();
        cm.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageHospitalsBtnActionPerformed

    private void managePoliceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePoliceBtnActionPerformed
        // TODO add your handling code here:
        PoliceAdminActivity pa = new PoliceAdminActivity();
        pa.setVisible(true);
        dispose();
    }//GEN-LAST:event_managePoliceBtnActionPerformed

    private void manageFireStationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageFireStationBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manageFireStationBtnActionPerformed

    private void manageCommAdminsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCommAdminsBtnActionPerformed
        // TODO add your handling code here:
        LegalDeptAdmin ld = new LegalDeptAdmin();
        ld.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageCommAdminsBtnActionPerformed

    private void manageEncountersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageEncountersBtnActionPerformed
        // TODO add your handling code here:
        DoctorManagementPortal dm = null;
        try {
            dm = new DoctorManagementPortal();
        } catch (SQLException ex) {
            Logger.getLogger(SysAdminJFrame1.class.getName()).log(Level.SEVERE, null, ex);
        }
        dm.setVisible(true);
        dispose();
    }//GEN-LAST:event_manageEncountersBtnActionPerformed

    private void homePageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePageBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homePageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SysAdminJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SysAdminJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SysAdminJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SysAdminJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SysAdminJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton homePageBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageCommAdminsBtn;
    private javax.swing.JButton manageEncountersBtn;
    private javax.swing.JButton manageFireStationBtn;
    private javax.swing.JButton manageHospitalBtn;
    private javax.swing.JButton manageHospitalsBtn;
    private javax.swing.JButton managePoliceBtn;
    // End of variables declaration//GEN-END:variables
}
